/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginCompleteRouteImport } from './routes/login_.complete'
import { Route as AccountCompleteRouteImport } from './routes/account_.complete'
import { Route as InvitationsTokenCompleteRouteImport } from './routes/invitations.$token.complete'
import { Route as InvitationsTokenAcceptRouteImport } from './routes/invitations.$token.accept'
import { Route as HostsHostIdWorkspacesRouteImport } from './routes/hosts.$hostId.workspaces'
import { Route as AccountOrganizationsOrgIdRouteImport } from './routes/account_.organizations.$orgId'
import { Route as HostsHostIdWorkspacesCreateRouteImport } from './routes/hosts.$hostId.workspaces_.create'
import { Route as HostsHostIdWorkspacesWorkspaceIdRouteImport } from './routes/hosts.$hostId.workspaces_.$workspaceId'
import { Route as HostsHostIdWorkspacesWorkspaceIdVscodeRouteImport } from './routes/hosts.$hostId.workspaces.$workspaceId.vscode'

const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCompleteRoute = LoginCompleteRouteImport.update({
  id: '/login_/complete',
  path: '/login/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountCompleteRoute = AccountCompleteRouteImport.update({
  id: '/account_/complete',
  path: '/account/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsTokenCompleteRoute =
  InvitationsTokenCompleteRouteImport.update({
    id: '/invitations/$token/complete',
    path: '/invitations/$token/complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const InvitationsTokenAcceptRoute = InvitationsTokenAcceptRouteImport.update({
  id: '/invitations/$token/accept',
  path: '/invitations/$token/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsHostIdWorkspacesRoute = HostsHostIdWorkspacesRouteImport.update({
  id: '/hosts/$hostId/workspaces',
  path: '/hosts/$hostId/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrganizationsOrgIdRoute =
  AccountOrganizationsOrgIdRouteImport.update({
    id: '/account_/organizations/$orgId',
    path: '/account/organizations/$orgId',
    getParentRoute: () => rootRouteImport,
  } as any)
const HostsHostIdWorkspacesCreateRoute =
  HostsHostIdWorkspacesCreateRouteImport.update({
    id: '/hosts/$hostId/workspaces_/create',
    path: '/hosts/$hostId/workspaces/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const HostsHostIdWorkspacesWorkspaceIdRoute =
  HostsHostIdWorkspacesWorkspaceIdRouteImport.update({
    id: '/hosts/$hostId/workspaces_/$workspaceId',
    path: '/hosts/$hostId/workspaces/$workspaceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const HostsHostIdWorkspacesWorkspaceIdVscodeRoute =
  HostsHostIdWorkspacesWorkspaceIdVscodeRouteImport.update({
    id: '/$workspaceId/vscode',
    path: '/$workspaceId/vscode',
    getParentRoute: () => HostsHostIdWorkspacesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/account/complete': typeof AccountCompleteRoute
  '/login/complete': typeof LoginCompleteRoute
  '/account/organizations/$orgId': typeof AccountOrganizationsOrgIdRoute
  '/hosts/$hostId/workspaces': typeof HostsHostIdWorkspacesRouteWithChildren
  '/invitations/$token/accept': typeof InvitationsTokenAcceptRoute
  '/invitations/$token/complete': typeof InvitationsTokenCompleteRoute
  '/hosts/$hostId/workspaces/$workspaceId': typeof HostsHostIdWorkspacesWorkspaceIdRoute
  '/hosts/$hostId/workspaces/create': typeof HostsHostIdWorkspacesCreateRoute
  '/hosts/$hostId/workspaces/$workspaceId/vscode': typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/account/complete': typeof AccountCompleteRoute
  '/login/complete': typeof LoginCompleteRoute
  '/account/organizations/$orgId': typeof AccountOrganizationsOrgIdRoute
  '/hosts/$hostId/workspaces': typeof HostsHostIdWorkspacesRouteWithChildren
  '/invitations/$token/accept': typeof InvitationsTokenAcceptRoute
  '/invitations/$token/complete': typeof InvitationsTokenCompleteRoute
  '/hosts/$hostId/workspaces/$workspaceId': typeof HostsHostIdWorkspacesWorkspaceIdRoute
  '/hosts/$hostId/workspaces/create': typeof HostsHostIdWorkspacesCreateRoute
  '/hosts/$hostId/workspaces/$workspaceId/vscode': typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/account_/complete': typeof AccountCompleteRoute
  '/login_/complete': typeof LoginCompleteRoute
  '/account_/organizations/$orgId': typeof AccountOrganizationsOrgIdRoute
  '/hosts/$hostId/workspaces': typeof HostsHostIdWorkspacesRouteWithChildren
  '/invitations/$token/accept': typeof InvitationsTokenAcceptRoute
  '/invitations/$token/complete': typeof InvitationsTokenCompleteRoute
  '/hosts/$hostId/workspaces_/$workspaceId': typeof HostsHostIdWorkspacesWorkspaceIdRoute
  '/hosts/$hostId/workspaces_/create': typeof HostsHostIdWorkspacesCreateRoute
  '/hosts/$hostId/workspaces/$workspaceId/vscode': typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/login'
    | '/notifications'
    | '/account/complete'
    | '/login/complete'
    | '/account/organizations/$orgId'
    | '/hosts/$hostId/workspaces'
    | '/invitations/$token/accept'
    | '/invitations/$token/complete'
    | '/hosts/$hostId/workspaces/$workspaceId'
    | '/hosts/$hostId/workspaces/create'
    | '/hosts/$hostId/workspaces/$workspaceId/vscode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/login'
    | '/notifications'
    | '/account/complete'
    | '/login/complete'
    | '/account/organizations/$orgId'
    | '/hosts/$hostId/workspaces'
    | '/invitations/$token/accept'
    | '/invitations/$token/complete'
    | '/hosts/$hostId/workspaces/$workspaceId'
    | '/hosts/$hostId/workspaces/create'
    | '/hosts/$hostId/workspaces/$workspaceId/vscode'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/login'
    | '/notifications'
    | '/account_/complete'
    | '/login_/complete'
    | '/account_/organizations/$orgId'
    | '/hosts/$hostId/workspaces'
    | '/invitations/$token/accept'
    | '/invitations/$token/complete'
    | '/hosts/$hostId/workspaces_/$workspaceId'
    | '/hosts/$hostId/workspaces_/create'
    | '/hosts/$hostId/workspaces/$workspaceId/vscode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  AccountCompleteRoute: typeof AccountCompleteRoute
  LoginCompleteRoute: typeof LoginCompleteRoute
  AccountOrganizationsOrgIdRoute: typeof AccountOrganizationsOrgIdRoute
  HostsHostIdWorkspacesRoute: typeof HostsHostIdWorkspacesRouteWithChildren
  InvitationsTokenAcceptRoute: typeof InvitationsTokenAcceptRoute
  InvitationsTokenCompleteRoute: typeof InvitationsTokenCompleteRoute
  HostsHostIdWorkspacesWorkspaceIdRoute: typeof HostsHostIdWorkspacesWorkspaceIdRoute
  HostsHostIdWorkspacesCreateRoute: typeof HostsHostIdWorkspacesCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/complete': {
      id: '/login_/complete'
      path: '/login/complete'
      fullPath: '/login/complete'
      preLoaderRoute: typeof LoginCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/complete': {
      id: '/account_/complete'
      path: '/account/complete'
      fullPath: '/account/complete'
      preLoaderRoute: typeof AccountCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/$token/complete': {
      id: '/invitations/$token/complete'
      path: '/invitations/$token/complete'
      fullPath: '/invitations/$token/complete'
      preLoaderRoute: typeof InvitationsTokenCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/$token/accept': {
      id: '/invitations/$token/accept'
      path: '/invitations/$token/accept'
      fullPath: '/invitations/$token/accept'
      preLoaderRoute: typeof InvitationsTokenAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$hostId/workspaces': {
      id: '/hosts/$hostId/workspaces'
      path: '/hosts/$hostId/workspaces'
      fullPath: '/hosts/$hostId/workspaces'
      preLoaderRoute: typeof HostsHostIdWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/organizations/$orgId': {
      id: '/account_/organizations/$orgId'
      path: '/account/organizations/$orgId'
      fullPath: '/account/organizations/$orgId'
      preLoaderRoute: typeof AccountOrganizationsOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$hostId/workspaces_/create': {
      id: '/hosts/$hostId/workspaces_/create'
      path: '/hosts/$hostId/workspaces/create'
      fullPath: '/hosts/$hostId/workspaces/create'
      preLoaderRoute: typeof HostsHostIdWorkspacesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$hostId/workspaces_/$workspaceId': {
      id: '/hosts/$hostId/workspaces_/$workspaceId'
      path: '/hosts/$hostId/workspaces/$workspaceId'
      fullPath: '/hosts/$hostId/workspaces/$workspaceId'
      preLoaderRoute: typeof HostsHostIdWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$hostId/workspaces/$workspaceId/vscode': {
      id: '/hosts/$hostId/workspaces/$workspaceId/vscode'
      path: '/$workspaceId/vscode'
      fullPath: '/hosts/$hostId/workspaces/$workspaceId/vscode'
      preLoaderRoute: typeof HostsHostIdWorkspacesWorkspaceIdVscodeRouteImport
      parentRoute: typeof HostsHostIdWorkspacesRoute
    }
  }
}

interface HostsHostIdWorkspacesRouteChildren {
  HostsHostIdWorkspacesWorkspaceIdVscodeRoute: typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
}

const HostsHostIdWorkspacesRouteChildren: HostsHostIdWorkspacesRouteChildren = {
  HostsHostIdWorkspacesWorkspaceIdVscodeRoute:
    HostsHostIdWorkspacesWorkspaceIdVscodeRoute,
}

const HostsHostIdWorkspacesRouteWithChildren =
  HostsHostIdWorkspacesRoute._addFileChildren(
    HostsHostIdWorkspacesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  AccountCompleteRoute: AccountCompleteRoute,
  LoginCompleteRoute: LoginCompleteRoute,
  AccountOrganizationsOrgIdRoute: AccountOrganizationsOrgIdRoute,
  HostsHostIdWorkspacesRoute: HostsHostIdWorkspacesRouteWithChildren,
  InvitationsTokenAcceptRoute: InvitationsTokenAcceptRoute,
  InvitationsTokenCompleteRoute: InvitationsTokenCompleteRoute,
  HostsHostIdWorkspacesWorkspaceIdRoute: HostsHostIdWorkspacesWorkspaceIdRoute,
  HostsHostIdWorkspacesCreateRoute: HostsHostIdWorkspacesCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
