/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingSignInRouteImport } from './routes/onboarding_.sign-in'
import { Route as AppWorkspacesRouteImport } from './routes/_app.workspaces'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as WorkspacesWorkspaceIdVscodeRouteImport } from './routes/workspaces.$workspaceId.vscode'
import { Route as AppWorkspacesCreateRouteImport } from './routes/_app.workspaces_.create'
import { Route as AppWorkspacesWorkspaceIdRouteImport } from './routes/_app.workspaces_.$workspaceId'
import { Route as AppHostsHostIdWorkspacesRouteImport } from './routes/_app.hosts.$hostId.workspaces'
import { Route as HostsHostIdWorkspacesWorkspaceIdVscodeRouteImport } from './routes/hosts.$hostId.workspaces.$workspaceId.vscode'
import { Route as AppHostsHostIdWorkspacesCreateRouteImport } from './routes/_app.hosts.$hostId.workspaces_.create'
import { Route as AppHostsHostIdWorkspacesWorkspaceIdRouteImport } from './routes/_app.hosts.$hostId.workspaces_.$workspaceId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSignInRoute = OnboardingSignInRouteImport.update({
  id: '/onboarding_/sign-in',
  path: '/onboarding/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspacesRoute = AppWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const WorkspacesWorkspaceIdVscodeRoute =
  WorkspacesWorkspaceIdVscodeRouteImport.update({
    id: '/workspaces/$workspaceId/vscode',
    path: '/workspaces/$workspaceId/vscode',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWorkspacesCreateRoute = AppWorkspacesCreateRouteImport.update({
  id: '/workspaces_/create',
  path: '/workspaces/create',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspacesWorkspaceIdRoute =
  AppWorkspacesWorkspaceIdRouteImport.update({
    id: '/workspaces_/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => AppRoute,
  } as any)
const AppHostsHostIdWorkspacesRoute =
  AppHostsHostIdWorkspacesRouteImport.update({
    id: '/hosts/$hostId/workspaces',
    path: '/hosts/$hostId/workspaces',
    getParentRoute: () => AppRoute,
  } as any)
const HostsHostIdWorkspacesWorkspaceIdVscodeRoute =
  HostsHostIdWorkspacesWorkspaceIdVscodeRouteImport.update({
    id: '/hosts/$hostId/workspaces/$workspaceId/vscode',
    path: '/hosts/$hostId/workspaces/$workspaceId/vscode',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppHostsHostIdWorkspacesCreateRoute =
  AppHostsHostIdWorkspacesCreateRouteImport.update({
    id: '/hosts/$hostId/workspaces_/create',
    path: '/hosts/$hostId/workspaces/create',
    getParentRoute: () => AppRoute,
  } as any)
const AppHostsHostIdWorkspacesWorkspaceIdRoute =
  AppHostsHostIdWorkspacesWorkspaceIdRouteImport.update({
    id: '/hosts/$hostId/workspaces_/$workspaceId',
    path: '/hosts/$hostId/workspaces/$workspaceId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/notifications': typeof AppNotificationsRoute
  '/workspaces': typeof AppWorkspacesRoute
  '/onboarding/sign-in': typeof OnboardingSignInRoute
  '/workspaces/$workspaceId': typeof AppWorkspacesWorkspaceIdRoute
  '/workspaces/create': typeof AppWorkspacesCreateRoute
  '/workspaces/$workspaceId/vscode': typeof WorkspacesWorkspaceIdVscodeRoute
  '/hosts/$hostId/workspaces': typeof AppHostsHostIdWorkspacesRoute
  '/hosts/$hostId/workspaces/$workspaceId': typeof AppHostsHostIdWorkspacesWorkspaceIdRoute
  '/hosts/$hostId/workspaces/create': typeof AppHostsHostIdWorkspacesCreateRoute
  '/hosts/$hostId/workspaces/$workspaceId/vscode': typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/notifications': typeof AppNotificationsRoute
  '/workspaces': typeof AppWorkspacesRoute
  '/onboarding/sign-in': typeof OnboardingSignInRoute
  '/workspaces/$workspaceId': typeof AppWorkspacesWorkspaceIdRoute
  '/workspaces/create': typeof AppWorkspacesCreateRoute
  '/workspaces/$workspaceId/vscode': typeof WorkspacesWorkspaceIdVscodeRoute
  '/hosts/$hostId/workspaces': typeof AppHostsHostIdWorkspacesRoute
  '/hosts/$hostId/workspaces/$workspaceId': typeof AppHostsHostIdWorkspacesWorkspaceIdRoute
  '/hosts/$hostId/workspaces/create': typeof AppHostsHostIdWorkspacesCreateRoute
  '/hosts/$hostId/workspaces/$workspaceId/vscode': typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/workspaces': typeof AppWorkspacesRoute
  '/onboarding_/sign-in': typeof OnboardingSignInRoute
  '/_app/workspaces_/$workspaceId': typeof AppWorkspacesWorkspaceIdRoute
  '/_app/workspaces_/create': typeof AppWorkspacesCreateRoute
  '/workspaces/$workspaceId/vscode': typeof WorkspacesWorkspaceIdVscodeRoute
  '/_app/hosts/$hostId/workspaces': typeof AppHostsHostIdWorkspacesRoute
  '/_app/hosts/$hostId/workspaces_/$workspaceId': typeof AppHostsHostIdWorkspacesWorkspaceIdRoute
  '/_app/hosts/$hostId/workspaces_/create': typeof AppHostsHostIdWorkspacesCreateRoute
  '/hosts/$hostId/workspaces/$workspaceId/vscode': typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/notifications'
    | '/workspaces'
    | '/onboarding/sign-in'
    | '/workspaces/$workspaceId'
    | '/workspaces/create'
    | '/workspaces/$workspaceId/vscode'
    | '/hosts/$hostId/workspaces'
    | '/hosts/$hostId/workspaces/$workspaceId'
    | '/hosts/$hostId/workspaces/create'
    | '/hosts/$hostId/workspaces/$workspaceId/vscode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/notifications'
    | '/workspaces'
    | '/onboarding/sign-in'
    | '/workspaces/$workspaceId'
    | '/workspaces/create'
    | '/workspaces/$workspaceId/vscode'
    | '/hosts/$hostId/workspaces'
    | '/hosts/$hostId/workspaces/$workspaceId'
    | '/hosts/$hostId/workspaces/create'
    | '/hosts/$hostId/workspaces/$workspaceId/vscode'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/onboarding'
    | '/_app/notifications'
    | '/_app/workspaces'
    | '/onboarding_/sign-in'
    | '/_app/workspaces_/$workspaceId'
    | '/_app/workspaces_/create'
    | '/workspaces/$workspaceId/vscode'
    | '/_app/hosts/$hostId/workspaces'
    | '/_app/hosts/$hostId/workspaces_/$workspaceId'
    | '/_app/hosts/$hostId/workspaces_/create'
    | '/hosts/$hostId/workspaces/$workspaceId/vscode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  OnboardingSignInRoute: typeof OnboardingSignInRoute
  WorkspacesWorkspaceIdVscodeRoute: typeof WorkspacesWorkspaceIdVscodeRoute
  HostsHostIdWorkspacesWorkspaceIdVscodeRoute: typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding_/sign-in': {
      id: '/onboarding_/sign-in'
      path: '/onboarding/sign-in'
      fullPath: '/onboarding/sign-in'
      preLoaderRoute: typeof OnboardingSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspaces': {
      id: '/_app/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AppWorkspacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/workspaces/$workspaceId/vscode': {
      id: '/workspaces/$workspaceId/vscode'
      path: '/workspaces/$workspaceId/vscode'
      fullPath: '/workspaces/$workspaceId/vscode'
      preLoaderRoute: typeof WorkspacesWorkspaceIdVscodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspaces_/create': {
      id: '/_app/workspaces_/create'
      path: '/workspaces/create'
      fullPath: '/workspaces/create'
      preLoaderRoute: typeof AppWorkspacesCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspaces_/$workspaceId': {
      id: '/_app/workspaces_/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hosts/$hostId/workspaces': {
      id: '/_app/hosts/$hostId/workspaces'
      path: '/hosts/$hostId/workspaces'
      fullPath: '/hosts/$hostId/workspaces'
      preLoaderRoute: typeof AppHostsHostIdWorkspacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/hosts/$hostId/workspaces/$workspaceId/vscode': {
      id: '/hosts/$hostId/workspaces/$workspaceId/vscode'
      path: '/hosts/$hostId/workspaces/$workspaceId/vscode'
      fullPath: '/hosts/$hostId/workspaces/$workspaceId/vscode'
      preLoaderRoute: typeof HostsHostIdWorkspacesWorkspaceIdVscodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/hosts/$hostId/workspaces_/create': {
      id: '/_app/hosts/$hostId/workspaces_/create'
      path: '/hosts/$hostId/workspaces/create'
      fullPath: '/hosts/$hostId/workspaces/create'
      preLoaderRoute: typeof AppHostsHostIdWorkspacesCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hosts/$hostId/workspaces_/$workspaceId': {
      id: '/_app/hosts/$hostId/workspaces_/$workspaceId'
      path: '/hosts/$hostId/workspaces/$workspaceId'
      fullPath: '/hosts/$hostId/workspaces/$workspaceId'
      preLoaderRoute: typeof AppHostsHostIdWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppWorkspacesRoute: typeof AppWorkspacesRoute
  AppWorkspacesWorkspaceIdRoute: typeof AppWorkspacesWorkspaceIdRoute
  AppWorkspacesCreateRoute: typeof AppWorkspacesCreateRoute
  AppHostsHostIdWorkspacesRoute: typeof AppHostsHostIdWorkspacesRoute
  AppHostsHostIdWorkspacesWorkspaceIdRoute: typeof AppHostsHostIdWorkspacesWorkspaceIdRoute
  AppHostsHostIdWorkspacesCreateRoute: typeof AppHostsHostIdWorkspacesCreateRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppNotificationsRoute: AppNotificationsRoute,
  AppWorkspacesRoute: AppWorkspacesRoute,
  AppWorkspacesWorkspaceIdRoute: AppWorkspacesWorkspaceIdRoute,
  AppWorkspacesCreateRoute: AppWorkspacesCreateRoute,
  AppHostsHostIdWorkspacesRoute: AppHostsHostIdWorkspacesRoute,
  AppHostsHostIdWorkspacesWorkspaceIdRoute:
    AppHostsHostIdWorkspacesWorkspaceIdRoute,
  AppHostsHostIdWorkspacesCreateRoute: AppHostsHostIdWorkspacesCreateRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  OnboardingSignInRoute: OnboardingSignInRoute,
  WorkspacesWorkspaceIdVscodeRoute: WorkspacesWorkspaceIdVscodeRoute,
  HostsHostIdWorkspacesWorkspaceIdVscodeRoute:
    HostsHostIdWorkspacesWorkspaceIdVscodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
